name: icmseg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchtriton=2.0.0
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyter
  - notebook
  - opencv-python
  - seaborn
  - pillow
  - requests
  - pyyaml
  - pip:
      - torchmetrics
      - transformers
      - timm
      - wandb
      - tensorboard
      - einops
      - albumentations
      - opendatalab
      - xformers
      - super-gradients
      - segmentation-models-pytorch
