method: UNetContrast
learning_rate: 1e-3
weight_decay: 1e-5
optimizer: AdamW
early_stop: 40
transforms: bigaug
loss_weight: None
task_name: unet1ch
norm_layer: SN
bilinear: True
layers: 32-64-128-256-512
loss_name: dice
batch_size: 64
filter: 0
lr_scheduler: coswarmup
precision: 32
num_epochs: 100
pretrained: False
ckpt_in: None
continue: False
rgb_dim: 1
out_dim: 128
temperature: 0.2
loss_contrast_weight: 1.0
loss_contrast: NTXentLossSegm
loss_style: 1
loss_source: 1